import HeaderWrapper from '@/components/Header/HeaderWrapper';
import Footer from "@/components/Footer/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="canonical" href="/" />
        <link rel="icon" type="image/x-icon" href="/assets/images/favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" type="text/css" href="/assets/vendor/magnific-popup/magnific-popup.min.css"/>
        <link rel="stylesheet" type="text/css" href="/assets/vendor/bootstrap-select/dist/css/bootstrap-select.min.css"/>
        <link rel="stylesheet" type="text/css" href="/assets/vendor/swiper/swiper-bundle.min.css"/>
        <link rel="stylesheet" type="text/css" href="/assets/vendor/animate/animate.css"/>
        {/* <link rel="stylesheet" type="text/css" href="vendor/lightgallery/dist/css/lightgallery.css"/> */}
        {/* <link rel="stylesheet" type="text/css" href="/assets/vendor/lightgallery/dist/css/lg-thumbnail.css"/>
        <link rel="stylesheet" type="text/css" href="/assets/vendor/lightgallery/dist/css/lg-zoom.css"/> */}
        <link rel="stylesheet" type="text/css" href="/assets/css/style.css"/>
        <link type="text/css" rel="stylesheet" href="/assets/css/skin/skin-1.css"/>
        
      </head>
      <body>
        <div className="page-wraper">
          <HeaderWrapper />
          {children}
          <Footer />
        </div>
        <script src="/assets/js/jquery.min.js" defer></script>
        <script src="/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js" defer></script>
      </body>
    </html>
  );
}